# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Akshay Kumar
email: aksh04ay@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A potpourri of ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aksh04ay.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: aksh04ay/aksh04ay.github.io
twitter: aksh04ay
github: aksh04ay
goodreads: 41356690-akshay-kumar
linkedin: akshay-kumar-b1254335

google_analytics:
comments: true
disqus: watery-jekyll

author: Akshay Kumar
author_bio: >-
  Hey there! 😄  My name is Akshay, I am a Senior Software Engineer at
  Sumo Logic working on data ingestion pipelines.
author_pic: img/avatar.jpg

paginate: 4
paginate_path: "/:num/"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
permalink: /:title

theme_switcher: true

# Allows all pages to be put into `_pages` folder
# for easier navigation and better SEO.
collections:
  pages:
    output: true
    permalink: /:title

# Exclude from processing.
exclude:
  - ".jekyll-cache"
  - "Gemfile"
  - "Gemfile.lock"
